# Generated by Django 3.0.6 on 2021-03-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210314_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.BigIntegerField()),
                ('question', models.CharField(max_length=500)),
                ('qtype', models.CharField(max_length=50)),
                ('mt_s', models.CharField(default='None', max_length=500)),
                ('mt_a', models.CharField(default='None', max_length=500)),
                ('mc_s', models.CharField(default='None', max_length=500)),
                ('mc_a', models.CharField(default='None', max_length=500)),
                ('fb_s', models.CharField(default='None', max_length=500)),
                ('fb_a', models.CharField(default='None', max_length=500)),
                ('tf_s', models.CharField(default='None', max_length=500)),
                ('tf_a', models.CharField(default='None', max_length=500)),
            ],
        ),
    ]
